ALTER SESSION

SET CONTAINER = ORCLPDB;

CREATE USER audit_manager_user IDENTIFIED BY admin123;

GRANT CONNECT
	,RESOURCE
	TO audit_manager_user;

ALTER USER audit_manager_user QUOTA UNLIMITED ON USERS;


CREATE TABLE user_mst (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name VARCHAR2(255) NOT NULL,
    password VARCHAR2(255) NOT NULL,
    active NUMBER(1) DEFAULT 1, -- BOOLEAN type is typically represented as 1 (true) and 0 (false) in Oracle
    profile_image_name VARCHAR2(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- default user

INSERT INTO user_mst (user_name, password, created_at, updated_at, active, profile_image_name)
VALUES ('admin', '$2a$10$bgR4EcS6I.nIT48XQSj.uO3epcGgWdfl.SbVIIK62FFV3./4KEcu6', 
        TO_TIMESTAMP('2024-04-18 13:46:12', 'YYYY-MM-DD HH24:MI:SS'), 
        TO_TIMESTAMP('2024-04-18 13:46:12', 'YYYY-MM-DD HH24:MI:SS'), 
        1, NULL);




